version: "3"

services:
  api:
    build: .
    container_name: api
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:13.1-alpine
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=gosho
      - POSTGRES_PASSWORD=losho
      - POSTGRES_DB=crud-playground
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
